### ISSUE TITLE
Add support for different languages

### ISSUE THREAD

**Issue by gudjonsi** [UksusoFF/webtrees-photos#1]
Great module. Is there a plan to add support for different languages? The text "Last # uploaded photos" appears in the module for all languages in webtrees. There is no "langs" folder under the "resources" folder with language file i.e. en.php to duplicate for translation for different languages.

**Comment by UksusoFF** [comment]
Check this commit: 
https://github.com/UksusoFF/webtrees-photos/commit/ba79c538b86ec2bb06023b0cd65ff4aa914cc331

**Comment by gudjonsi** [comment]
Great, thanks for the quick response and solution.
